CREATE TABLE Categories
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    symbol_code VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Users
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL,
    password VARCHAR(200) NOT NULL,
    contacts VARCHAR(200) NOT NULL
);

CREATE TABLE Lots
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    creator_id INT NOT NULL,
    winner_id INT NULL,
    category_id INT NOT NULL,
    created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(500) NOT NULL,
    img VARCHAR(200) NOT NULL,
    start_price INT UNSIGNED NOT NULL,
    step_price INT UNSIGNED NOT NULL,
    date_finished DATE NOT NULL,
    FOREIGN KEY (creator_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (winner_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES Categories(id) ON DELETE CASCADE
);

CREATE TABLE Bets
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    lot_id INT NOT NULL,
    created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    price INT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (lot_id) REFERENCES Lots(id) ON DELETE CASCADE
);